version: '3.3'

services:
  db: # Cotainer de MySQL
    image: mysql:5.7 # FROM mysql:5.7
    volumes: 
      - db_data:/var/mysql
    restart: always #compose executando sempre na ultima atualização
    env_file:
      - ./config/db.env
    networks:
      - backend

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports: 
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env
    networks:
      - backend

volumes:
  db_data: {}
networks:
  backend:
    driver: bridge