apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask
          image: gabrielao/flask-kub-projeto:5
          # image: gabrielao/flask-kub-projeto:2
          # image: gabrielao/flask-kub-projeto

# execut
